// Generated by scripts/index-catalogue-files.js on 2025-07-27T03:58:23.566Z

declare module '../scripts/catalogue-index.js' {
  export interface SiteCategory {
    site: string;
    category_en: string;
    category_ms: string;
    category_sort: number;
    subcategory_en: string;
    subcategory_ms: string;
    subcategory_sort: number;
  }

  export interface DatasetMetadata {
    id: string;
    title_en: string;
    title_ms: string;
    description_en: string;
    description_ms: string;
    frequency: string;
    geography: string[];
    demography: string[];
    dataset_begin: number | null;
    dataset_end: number | null;
    data_source: string[];
    data_as_of: string;
    last_updated: string;
    next_update: string;
    link_parquet: string;
    link_csv: string;
    link_preview: string;
    site_category: SiteCategory[];
  }

  export interface CatalogueFilters {
    categories: string[];
    geographies: string[];
    frequencies: string[];
    demographies: string[];
    dataSources: string[];
  }

  export const CATALOGUE_INDEX: DatasetMetadata[];
  export const CATALOGUE_FILTERS: CatalogueFilters;
}